package com.hp.pojo;
// Generated Aug 14, 2014 6:05:37 PM by Hibernate Tools 3.6.0



/**
 * Questionanswer generated by hbm2java
 */
public class Questionanswer  implements java.io.Serializable {


     private Integer quesId;
     private int voterIdentityNumber;
     private Integer cid;
     private String question;
     private String answer;
     private String status;

    public Questionanswer() {
    }

	
    public Questionanswer(int voterIdentityNumber, String question, String answer) {
        this.voterIdentityNumber = voterIdentityNumber;
        this.question = question;
        this.answer = answer;
    }
    public Questionanswer(int voterIdentityNumber, Integer cid, String question, String answer, String status) {
       this.voterIdentityNumber = voterIdentityNumber;
       this.cid = cid;
       this.question = question;
       this.answer = answer;
       this.status = status;
    }
   
    public Integer getQuesId() {
        return this.quesId;
    }
    
    public void setQuesId(Integer quesId) {
        this.quesId = quesId;
    }
    public int getVoterIdentityNumber() {
        return this.voterIdentityNumber;
    }
    
    public void setVoterIdentityNumber(int voterIdentityNumber) {
        this.voterIdentityNumber = voterIdentityNumber;
    }
    public Integer getCid() {
        return this.cid;
    }
    
    public void setCid(Integer cid) {
        this.cid = cid;
    }
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


