package com.hp.pojo;
// Generated Aug 14, 2014 6:05:37 PM by Hibernate Tools 3.6.0



/**
 * City generated by hbm2java
 */
public class City  implements java.io.Serializable {


     private int cityCode;
     private String cityName;

    public City() {
    }

    public City(int cityCode, String cityName) {
       this.cityCode = cityCode;
       this.cityName = cityName;
    }
   
    public int getCityCode() {
        return this.cityCode;
    }
    
    public void setCityCode(int cityCode) {
        this.cityCode = cityCode;
    }
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }




}


