package com.hp.pojo;
// Generated Aug 14, 2014 6:05:37 PM by Hibernate Tools 3.6.0



/**
 * Electionresult generated by hbm2java
 */
public class Electionresult  implements java.io.Serializable {


     private Integer resultId;
     private int pcode;
     private int cityCode;
     private String candidateName;
     private int electionYear;
     private int totalVotes;

    public Electionresult() {
    }

    public Electionresult(int pcode, int cityCode, String candidateName, int electionYear, int totalVotes) {
       this.pcode = pcode;
       this.cityCode = cityCode;
       this.candidateName = candidateName;
       this.electionYear = electionYear;
       this.totalVotes = totalVotes;
    }
   
    public Integer getResultId() {
        return this.resultId;
    }
    
    public void setResultId(Integer resultId) {
        this.resultId = resultId;
    }
    public int getPcode() {
        return this.pcode;
    }
    
    public void setPcode(int pcode) {
        this.pcode = pcode;
    }
    public int getCityCode() {
        return this.cityCode;
    }
    
    public void setCityCode(int cityCode) {
        this.cityCode = cityCode;
    }
    public String getCandidateName() {
        return this.candidateName;
    }
    
    public void setCandidateName(String candidateName) {
        this.candidateName = candidateName;
    }
    public int getElectionYear() {
        return this.electionYear;
    }
    
    public void setElectionYear(int electionYear) {
        this.electionYear = electionYear;
    }
    public int getTotalVotes() {
        return this.totalVotes;
    }
    
    public void setTotalVotes(int totalVotes) {
        this.totalVotes = totalVotes;
    }




}


