package com.hp.pojo;
// Generated Aug 14, 2014 6:05:37 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Electiondetails generated by hbm2java
 */
public class Electiondetails  implements java.io.Serializable {


     private Integer year;
     private Date electiondate;

    public Electiondetails() {
    }

    public Electiondetails(Date electiondate) {
       this.electiondate = electiondate;
    }
   
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    public Date getElectiondate() {
        return this.electiondate;
    }
    
    public void setElectiondate(Date electiondate) {
        this.electiondate = electiondate;
    }




}


