package com.hp.pojo;
// Generated Aug 14, 2014 6:05:37 PM by Hibernate Tools 3.6.0



/**
 * Politicalparty generated by hbm2java
 */
public class Politicalparty  implements java.io.Serializable {


     private int pcode;
     private String pname;
     private byte[] emblem;

    public Politicalparty() {
    }

	
    public Politicalparty(int pcode, String pname) {
        this.pcode = pcode;
        this.pname = pname;
    }
    public Politicalparty(int pcode, String pname, byte[] emblem) {
       this.pcode = pcode;
       this.pname = pname;
       this.emblem = emblem;
    }
   
    public int getPcode() {
        return this.pcode;
    }
    
    public void setPcode(int pcode) {
        this.pcode = pcode;
    }
    public String getPname() {
        return this.pname;
    }
    
    public void setPname(String pname) {
        this.pname = pname;
    }
    public byte[] getEmblem() {
        return this.emblem;
    }
    
    public void setEmblem(byte[] emblem) {
        this.emblem = emblem;
    }




}


