package com.hp.pojo;
// Generated Aug 14, 2014 6:05:37 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Voter generated by hbm2java
 */
public class Voter  implements java.io.Serializable {


     private int voterIdentityNumber;
     private String fname;
     private String mname;
     private String lname;
     private String gender;
     private Date dob;
     private String email;
     private int cityCode;
     private String fathersName;
     private String mothersName;
     private byte[] voterIdentityCard;
     private Boolean voterStatus;
     private Boolean hasVoted;

    public Voter() {
    }

	
    public Voter(int voterIdentityNumber, String fname, String mname, String lname, String gender, Date dob, String email, int cityCode, String fathersName, String mothersName) {
        this.voterIdentityNumber = voterIdentityNumber;
        this.fname = fname;
        this.mname = mname;
        this.lname = lname;
        this.gender = gender;
        this.dob = dob;
        this.email = email;
        this.cityCode = cityCode;
        this.fathersName = fathersName;
        this.mothersName = mothersName;
    }
    public Voter(int voterIdentityNumber, String fname, String mname, String lname, String gender, Date dob, String email, int cityCode, String fathersName, String mothersName, byte[] voterIdentityCard, Boolean voterStatus, Boolean hasVoted) {
       this.voterIdentityNumber = voterIdentityNumber;
       this.fname = fname;
       this.mname = mname;
       this.lname = lname;
       this.gender = gender;
       this.dob = dob;
       this.email = email;
       this.cityCode = cityCode;
       this.fathersName = fathersName;
       this.mothersName = mothersName;
       this.voterIdentityCard = voterIdentityCard;
       this.voterStatus = voterStatus;
       this.hasVoted = hasVoted;
    }
   
    public int getVoterIdentityNumber() {
        return this.voterIdentityNumber;
    }
    
    public void setVoterIdentityNumber(int voterIdentityNumber) {
        this.voterIdentityNumber = voterIdentityNumber;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getMname() {
        return this.mname;
    }
    
    public void setMname(String mname) {
        this.mname = mname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getCityCode() {
        return this.cityCode;
    }
    
    public void setCityCode(int cityCode) {
        this.cityCode = cityCode;
    }
    public String getFathersName() {
        return this.fathersName;
    }
    
    public void setFathersName(String fathersName) {
        this.fathersName = fathersName;
    }
    public String getMothersName() {
        return this.mothersName;
    }
    
    public void setMothersName(String mothersName) {
        this.mothersName = mothersName;
    }
    public byte[] getVoterIdentityCard() {
        return this.voterIdentityCard;
    }
    
    public void setVoterIdentityCard(byte[] voterIdentityCard) {
        this.voterIdentityCard = voterIdentityCard;
    }
    public Boolean getVoterStatus() {
        return this.voterStatus;
    }
    
    public void setVoterStatus(Boolean voterStatus) {
        this.voterStatus = voterStatus;
    }
    public Boolean getHasVoted() {
        return this.hasVoted;
    }
    
    public void setHasVoted(Boolean hasVoted) {
        this.hasVoted = hasVoted;
    }




}


